-- =============================================================================
-- Network Operations — Synthetic Data Generation
-- =============================================================================
-- Generates demo-quality data for all ops tables.
-- Designed for Snowhouse dev (TEMP database).
-- For customer deployments, change TEMP -> NETWORK_OPERATIONS and
-- NETWORK_OPS_ANALYTICS -> ANALYTICS throughout.
-- =============================================================================

USE ROLE PRODUCT_MANAGER;
USE WAREHOUSE APP_THOUGHTSPOT_OAUTH_WH;  -- must be a STANDARD warehouse (not INTERACTIVE)
USE DATABASE TEMP;
USE SCHEMA NETWORK_OPS_ANALYTICS;

-- 450 cell sites across 5 Portugal cities
CREATE OR REPLACE TABLE DIM_CELL_SITE AS
SELECT
    'CELL-' || LPAD((SEQ4()+1)::VARCHAR, 4, '0') AS CELL_ID,
    'SITE-' || LPAD((SEQ4()+1)::VARCHAR, 4, '0') AS SITE_ID,
    'NODE-' || LPAD((SEQ4()+1)::VARCHAR, 4, '0') AS NODE_ID,
    IFF(MOD(SEQ4(), 3) = 0, '5G', '4G')          AS TECHNOLOGY,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN 38.72 + UNIFORM(-0.08::FLOAT, 0.08::FLOAT, RANDOM())
        WHEN 1 THEN 41.16 + UNIFORM(-0.06::FLOAT, 0.06::FLOAT, RANDOM())
        WHEN 2 THEN 41.55 + UNIFORM(-0.04::FLOAT, 0.04::FLOAT, RANDOM())
        WHEN 3 THEN 40.20 + UNIFORM(-0.03::FLOAT, 0.03::FLOAT, RANDOM())
        ELSE      37.02 + UNIFORM(-0.03::FLOAT, 0.03::FLOAT, RANDOM())
    END AS LOCATION_LAT,
    CASE MOD(SEQ4(), 5)
        WHEN 0 THEN -9.14 + UNIFORM(-0.08::FLOAT, 0.08::FLOAT, RANDOM())
        WHEN 1 THEN -8.63 + UNIFORM(-0.06::FLOAT, 0.06::FLOAT, RANDOM())
        WHEN 2 THEN -8.43 + UNIFORM(-0.04::FLOAT, 0.04::FLOAT, RANDOM())
        WHEN 3 THEN -8.41 + UNIFORM(-0.03::FLOAT, 0.03::FLOAT, RANDOM())
        ELSE      -7.93 + UNIFORM(-0.03::FLOAT, 0.03::FLOAT, RANDOM())
    END AS LOCATION_LON,
    'TDV-' || LPAD((SEQ4()+1)::VARCHAR, 4, '0')  AS TRANSPORT_DEVICE_ID,
    'TIF-' || LPAD((SEQ4()+1)::VARCHAR, 4, '0')  AS TRANSPORT_INTERFACE_ID,
    CASE MOD(SEQ4(), 5) WHEN 0 THEN 'Lisboa' WHEN 1 THEN 'Norte' WHEN 2 THEN 'Norte' WHEN 3 THEN 'Centro' ELSE 'Algarve' END AS REGION,
    CASE MOD(SEQ4(), 5) WHEN 0 THEN 'Lisboa' WHEN 1 THEN 'Porto' WHEN 2 THEN 'Braga' WHEN 3 THEN 'Coimbra' ELSE 'Faro' END AS CITY,
    DATEADD('day', -UNIFORM(0, 1825, RANDOM()), '2025-09-30'::DATE) AS INSTALLATION_DATE,
    'ACTIVE' AS STATUS
FROM TABLE(GENERATOR(ROWCOUNT => 450));

-- ~83K RAN performance records (450 sites x 192 intervals = 48h of 15-min data)
CREATE OR REPLACE TABLE FACT_RAN_PERFORMANCE AS
SELECT
    DATEADD('minute', (MOD(N-1, 192))*15, '2025-09-29 00:00:00'::TIMESTAMP_NTZ) AS TIMESTAMP,
    'CELL-' || LPAD((MOD(N-1, 450)+1)::VARCHAR, 4, '0')   AS CELL_ID,
    IFF(MOD(N-1, 3) = 0, '5G', '4G')                      AS TECHNOLOGY,
    UNIFORM(800,  1000, RANDOM())                           AS RRC_CONNESTABATT,
    UNIFORM(760,  1000, RANDOM())                           AS RRC_CONNESTABSUCC,
    ROUND(UNIFORM(40.0::FLOAT,  95.0::FLOAT, RANDOM()), 2) AS DL_PRB_UTILIZATION,
    ROUND(UNIFORM(30.0::FLOAT,  85.0::FLOAT, RANDOM()), 2) AS UL_PRB_UTILIZATION,
    ROUND(UNIFORM(97.0::FLOAT, 100.0::FLOAT, RANDOM()), 3) AS CELL_AVAILABILITY,
    ROUND(IFF(MOD(N-1,3)=0, UNIFORM(50.0::FLOAT,250.0::FLOAT,RANDOM()),
                             UNIFORM(15.0::FLOAT, 80.0::FLOAT,RANDOM())), 2) AS DL_THROUGHPUT_MBPS,
    ROUND(IFF(MOD(N-1,3)=0, UNIFORM(20.0::FLOAT,120.0::FLOAT,RANDOM()),
                             UNIFORM(5.0::FLOAT,  40.0::FLOAT,RANDOM())), 2) AS UL_THROUGHPUT_MBPS,
    UNIFORM(50, 200, RANDOM())                              AS HANDOVER_ATTEMPTS,
    UNIFORM(45, 200, RANDOM())                              AS HANDOVER_SUCCESSES,
    ROUND(UNIFORM(92.0::FLOAT, 99.9::FLOAT, RANDOM()), 3)  AS ERAB_ESTABSUCCRATE,
    ROUND(UNIFORM(93.0::FLOAT, 99.9::FLOAT, RANDOM()), 3)  AS PDU_SESSESTABSUCCRATE
FROM (SELECT SEQ4()+1 AS N FROM TABLE(GENERATOR(ROWCOUNT => 86400)));

-- 2000 alarms (1700 resolved, 300 active/unreviewed for triage demo)
CREATE OR REPLACE TABLE ALARMS AS
SELECT
    'ALM-' || LPAD(N::VARCHAR, 5, '0')  AS ALARM_ID,
    'CELL-' || LPAD((MOD(N-1, 450)+1)::VARCHAR, 4, '0') AS CELL_ID,
    CASE MOD(N-1, 5) WHEN 0 THEN 'Lisboa' WHEN 1 THEN 'Porto' WHEN 2 THEN 'Braga' WHEN 3 THEN 'Coimbra' ELSE 'Faro' END AS CITY,
    CASE MOD(N-1, 5) WHEN 0 THEN 'Lisboa' WHEN 1 THEN 'Norte' WHEN 2 THEN 'Norte' WHEN 3 THEN 'Centro' ELSE 'Algarve' END AS REGION,
    IFF(MOD(N-1, 3) = 0, '5G', '4G') AS TECHNOLOGY,
    CASE MOD(N-1, 10) WHEN 0 THEN 'P1' WHEN 1 THEN 'P1' WHEN 2 THEN 'P2' WHEN 3 THEN 'P2' WHEN 4 THEN 'P2' ELSE 'P3' END AS SEVERITY,
    CASE MOD(N-1, 6)
        WHEN 0 THEN 'HIGH_PRB_UTILIZATION'  WHEN 1 THEN 'LOW_RRC_SUCCESS'
        WHEN 2 THEN 'CELL_UNAVAILABLE'      WHEN 3 THEN 'HIGH_LATENCY'
        WHEN 4 THEN 'HANDOVER_FAILURE'      ELSE 'THROUGHPUT_DEGRADATION'
    END AS ALARM_TYPE,
    DATEADD('minute', -UNIFORM(0, 2880, RANDOM()), CURRENT_TIMESTAMP()) AS ALARM_TIME,
    IFF(N <= 1700, 'RESOLVED', 'ACTIVE') AS STATUS,
    IFF(N <= 1700, TRUE, FALSE)          AS AI_REVIEWED
FROM (SELECT SEQ4()+1 AS N FROM TABLE(GENERATOR(ROWCOUNT => 2000)));

-- SLA targets per site
CREATE OR REPLACE TABLE SLA_TARGETS AS
SELECT
    CELL_ID, CITY, REGION,
    95.0  AS RRC_SUCCESS_RATE_TARGET,
    85.0  AS MAX_PRB_UTILIZATION,
    99.5  AS AVAILABILITY_TARGET,
    10.0  AS MIN_DL_THROUGHPUT_MBPS,
    60.0  AS MTTD_TARGET_MINUTES,
    240.0 AS MTTR_TARGET_MINUTES
FROM DIM_CELL_SITE;

-- Teams and engineers
CREATE OR REPLACE TABLE TEAMS (TEAM_ID VARCHAR(20), TEAM_NAME VARCHAR(100), SPECIALTY VARCHAR(50));
INSERT INTO TEAMS VALUES
    ('T001','Network Ops L1','RAN'), ('T002','Network Ops L2','Core'),
    ('T003','Core Network','Transport'), ('T004','Senior Engineers','All');

CREATE OR REPLACE TABLE ENGINEERS (ENGINEER_ID VARCHAR(20), NAME VARCHAR(100), TEAM_ID VARCHAR(20), SHIFT VARCHAR(20));
INSERT INTO ENGINEERS VALUES
    ('E001','Ana Costa','T001','Day'), ('E002','Pedro Ferreira','T001','Night'),
    ('E003','Maria Silva','T001','Day'), ('E004','João Santos','T002','Day'),
    ('E005','Sofia Rodrigues','T002','Night'), ('E006','Carlos Pereira','T003','Day'),
    ('E007','Inês Carvalho','T003','Night'), ('E008','Miguel Oliveira','T004','Day');

-- AI audit tables
USE SCHEMA NETWORK_OPS_AI;

CREATE OR REPLACE TABLE TRIAGE_RUNS (
    RUN_ID          VARCHAR(50),
    ALARM_ID        VARCHAR(50),
    CELL_ID         VARCHAR(50),
    ALARM_TYPE      VARCHAR(100),
    SEVERITY        VARCHAR(10),
    PROBABLE_CAUSE  VARCHAR(2000),
    AGENT_SEVERITY  VARCHAR(10),
    RECOMMENDED_ACTION VARCHAR(500),
    ANALYST_ACTION  VARCHAR(20),  -- ACCEPT | OVERRIDE | SUPPRESS | ESCALATE
    OVERRIDE_REASON VARCHAR(500),
    AGENT_REASONING VARIANT,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR(100)  DEFAULT CURRENT_USER()
);

CREATE OR REPLACE TABLE ASSIST_OUTPUTS (
    OUTPUT_ID       VARCHAR(50),
    REPORT_TYPE     VARCHAR(50),  -- INCIDENT_SUMMARY | SLA_COMPLIANCE | SHIFT_HANDOVER
    ALARM_ID        VARCHAR(50),
    REPORT_PERIOD   VARCHAR(50),
    CONTENT         VARCHAR(16000),
    STATUS          VARCHAR(20) DEFAULT 'DRAFT',  -- DRAFT | APPROVED | SENT
    APPROVED_BY     VARCHAR(100),
    APPROVED_AT     TIMESTAMP_NTZ,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR(100)  DEFAULT CURRENT_USER()
);

-- Verify
USE SCHEMA NETWORK_OPS_ANALYTICS;
SELECT 'DIM_CELL_SITE'       AS T, COUNT(*) AS N FROM DIM_CELL_SITE
UNION ALL SELECT 'FACT_RAN_PERFORMANCE', COUNT(*) FROM FACT_RAN_PERFORMANCE
UNION ALL SELECT 'ALARMS',              COUNT(*) FROM ALARMS
UNION ALL SELECT 'SLA_TARGETS',         COUNT(*) FROM SLA_TARGETS
UNION ALL SELECT 'TEAMS',               COUNT(*) FROM TEAMS
UNION ALL SELECT 'ENGINEERS',           COUNT(*) FROM ENGINEERS
ORDER BY T;
